{
 "title": "aviation project dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "User Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время на авторизацию пользователя",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(authenticateUser_seconds_sum[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время на регистрацию пользователей",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg(increase(registerUser_seconds_sum[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Order", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Время на поиск альтернативных полётов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(increase(findAltFlights_seconds_sum[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время на получение списка обслуживаний",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg(increase(findAllExamination_seconds_sum[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время на получение аэропортов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(increase(findAllAirports_seconds_sum[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Catering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Время на получение отдельной заявки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(increase(findOrder_seconds_sum[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время на получение почтовых адресов Caterer сотрудников",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "increase(getCatererEmails_seconds_max[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Число доставленных продуктов в выполненных заявках",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "productCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время получения всех заявок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "avg(increase(findAllOrderWithPageable_seconds_sum[24h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}