server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: flight-catering
          uri: lb://flight-catering
          predicates:
            - Path=/flight-catering/**
          filters:
            - StripPrefix=1
        - id: flight-order
          uri: lb://flight-order
          predicates:
            - Path=/flight-order/**
          filters:
            - StripPrefix=1
        - id: flight-user
          uri: lb://flight-user
          predicates:
            - Path=/flight-user/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
token:
  prefix: Bearer
